-- MySQL Script generated by MySQL Workbench
-- Sat Jan 25 23:25:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `mydb`;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `id_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `clave` INT(11) NOT NULL AUTO_INCREMENT,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Tipo_id_tipo` INT NOT NULL,
  PRIMARY KEY (`clave`),
  INDEX `fk_Usuario_Tipo_idx` (`Tipo_id_tipo` ASC),
  CONSTRAINT `fk_Usuario_Tipo`
    FOREIGN KEY (`Tipo_id_tipo`)
    REFERENCES `mydb`.`Tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `numero_mesa` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`numero_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comanda` (
  `id_comanda` INT(11) NOT NULL AUTO_INCREMENT,
  `hora_apertura` DATETIME NOT NULL,
  `numero_personas` INT NOT NULL,
  `Usuario_clave` INT NOT NULL,
  `Mesa_numero_mesa` INT NOT NULL,
  PRIMARY KEY (`id_comanda`),
  INDEX `fk_Comanda_Usuario1_idx` (`Usuario_clave` ASC),
  INDEX `fk_Comanda_Mesa1_idx` (`Mesa_numero_mesa` ASC),
  CONSTRAINT `fk_Comanda_Usuario1`
    FOREIGN KEY (`Usuario_clave`)
    REFERENCES `mydb`.`Usuario` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comanda_Mesa1`
    FOREIGN KEY (`Mesa_numero_mesa`)
    REFERENCES `mydb`.`Mesa` (`numero_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Platillo` (
  `id_platillo` INT(11) NOT NULL AUTO_INCREMENT,
  `precio` DOUBLE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_platillo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `id_Pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NOT NULL,
  `Comanda_id_comanda` INT(11) NOT NULL,
  `Platillo_id_platillo` INT(11) NOT NULL,
  INDEX `fk_Pedido_Comanda1_idx` (`Comanda_id_comanda` ASC),
  PRIMARY KEY (`id_Pedido`),
  INDEX `fk_Pedido_Platillo1_idx` (`Platillo_id_platillo` ASC),
  CONSTRAINT `fk_Pedido_Comanda1`
    FOREIGN KEY (`Comanda_id_comanda`)
    REFERENCES `mydb`.`Comanda` (`id_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Platillo1`
    FOREIGN KEY (`Platillo_id_platillo`)
    REFERENCES `mydb`.`Platillo` (`id_platillo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `id_ticket` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `hora` DATETIME NOT NULL,
  `iva` FLOAT NOT NULL,
  `metodo` VARCHAR(45) NOT NULL,
  `total` DOUBLE NOT NULL,
  `Comanda_id_comanda` INT(11) NOT NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `fk_Ticket_Comanda1_idx` (`Comanda_id_comanda` ASC),
  CONSTRAINT `fk_Ticket_Comanda1`
    FOREIGN KEY (`Comanda_id_comanda`)
    REFERENCES `mydb`.`Comanda` (`id_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `mydb`.`platillo` (precio, nombre, categoria, estado) VALUES
-- COMBINACIONES
(84, "Con Jamos, Tocino, Salchica, ó Longaniza", "Huevos", "disponible"),
(84, "Al Albañil", "Huevos", "disponible"),
(84, "A la Mexicana", "Huevos", "disponible"),
(84, "Tirados", "Huevos", "disponible"),
(97, "Longaniza en Salsa Roja", "Con Hambre", "disponibles"),
(97, "Puntas de Filete a la Mexicana", "Con Hambre", "disponibles"),
(97, "Chicarron en Salaa Verde o Salsa Roja", "Con Hambre", "disponibles"),
(97, "Chilaquiles Rojos o Verdes", "Con Hambre", "disponibles"),
(75, "Tlayoyos", "Del Comal", "disponibles"),
(75, "Quesadilla Natural", "Del Comal", "disponibles"),
(75, "Trilogía de picaditas", "Del Comal", "disponibles"),
(75, "Memela Trsdicional", "Del Comal", "disponibles"),
(75, "Gorditas Jarochas", "Del Comal", "disponibles"),
-- LA CARTA
(79, "Huevos Rancheros", "La Carta", "disponibles"),
(97, "Huevos con Machaca", "La Carta", "disponibles"),
(89, "Huevos Achichcarrados", "La Carta", "disponibles"),
(70, 'Costra Especial "El Patio"' , "La Carta", "disponibles"),
(120, 'Costra Especial "El Patio"' , "La Carta", "disponibles"),
(86, 'Huevos en Casuela con Jocoque' , "La Carta", "disponibles"),
(89, 'Huevos del Mercado' , "La Carta", "disponibles"),
(81, 'Omelette' , "La Carta", "disponibles"),
(97, 'Omelette Poblano' , "La Carta", "disponibles"),
(89, 'Enchiladas' , "La Carta", "disponibles"),
(99, 'Enchiladas Suizas' , "La Carta", "disponibles"),
(85, 'Enfrijoladas "El Patio"' , "La Carta", "disponibles"),
(119, 'Cecina' , "La Carta", "disponibles"),
(99, 'Tacos de Cecina' , "La Carta", "disponibles"),
(79, 'Huevos Motuleños' , "La Carta", "disponibles"),
(53, 'Plato de fruta' , "La Carta", "disponibles"),
(46, 'Enzalada de Manzana' , "La Carta", "disponibles"),
(71, 'Hot Cakes (3 pzas.)' , "La Carta", "disponibles"),
(15, 'Pan de Dulce (de la casa)' , "La Carta", "disponibles"),
-- BEBIDAS
(25, 'Americano' , "Bebidas calientes", "disponibles"),
(31, 'Expresso' , "Bebidas calientes", "disponibles"),
(32, 'Capuccino' , "Bebidas calientes", "disponibles"),
(35, 'Lechero' , "Bebidas calientes", "disponibles"),
(23, 'Té' , "Bebidas calientes", "disponibles"),
(33, 'Chocolate' , "Bebidas calientes", "disponibles"),
(25, 'Vaso Leche Chico' , "Bebidas calientes", "disponibles"),
(30, 'Vaso Leche Grande' , "Bebidas calientes", "disponibles"),
(35, 'Latte' , "Bebidas calientes", "disponibles"),

(39, 'Malteadas Fresa' , "Bebidas frias", "disponibles"),
(39, 'Malteadas Vainilla' , "Bebidas frias", "disponibles"),
(39, 'Malteadas Chocolate' , "Bebidas frias", "disponibles"),
(49, 'Ichi-koi Moka Oreo' , "Bebidas frias", "disponibles"),
(49, 'Ichi-koi Chips Ahoy' , "Bebidas frias", "disponibles"),
(49, 'Ichi-koi Clásico' , "Bebidas frias", "disponibles"),
(33, 'Chocomilk' , "Bebidas frias", "disponibles"),

(29, 'Vampiro. Chico(275 ml)' , "Bebidas Jugos", "disponibles"),
(37, 'Vampiro. Grnade(465 ml)' , "Bebidas Jugos", "disponibles"),
(29, 'Osasis. Chico(275 ml)' , "Bebidas Jugos", "disponibles"),
(37, 'Osasis. Grnade(465 ml)' , "Bebidas Jugos", "disponibles"),
(29, 'Verde. Chico(275 ml)' , "Bebidas Jugos", "disponibles"),
(37, 'Verde. Grnade(465 ml)' , "Bebidas Jugos", "disponibles"),

(31, "Cerveza", "Bebidas Pal' Alma", "disponibles"),
(39, "Michelada", "Bebidas Pal' Alma", "disponibles"),
(47, "Chelada", "Bebidas Pal' Alma", "disponibles"),

(28, "Refresco", "Bebidas Las Que Refrescan", "disponibles"),
(32, "Agua Mineral", "Bebidas Las Que Refrescan", "disponibles"),
(20, "Agua Embotellada", "Bebidas Las Que Refrescan", "disponibles"),
(35, "Soda Italiana", "Bebidas Las Que Refrescan", "disponibles"),
(32, "Rusa", "Bebidas Las Que Refrescan", "disponibles"),
(30, "Limonada", "Bebidas Las Que Refrescan", "disponibles"),
(30, "Naranjada", "Bebidas Las Que Refrescan", "disponibles"),
(42, "Agua de fresa con Avena", "Bebidas Las Que Refrescan", "disponibles"),
(35, "Lemon Stick", "Bebidas Las Que Refrescan", "disponibles"),
(35, "Conga", "Bebidas Las Que Refrescan", "disponibles");
select * from mydb.platillo;

INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Ocupado');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
