-- MySQL Script generated by MySQL Workbench
-- Sat Jan 25 23:25:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `mydb`;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `id_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `clave` INT(11) NOT NULL AUTO_INCREMENT,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Tipo_id_tipo` INT NOT NULL,
  PRIMARY KEY (`clave`),
  INDEX `fk_Usuario_Tipo_idx` (`Tipo_id_tipo` ASC),
  CONSTRAINT `fk_Usuario_Tipo`
    FOREIGN KEY (`Tipo_id_tipo`)
    REFERENCES `mydb`.`Tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `numero_mesa` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`numero_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comanda` (
  `id_comanda` INT(11) NOT NULL AUTO_INCREMENT,
  `hora_apertura` DATETIME NOT NULL,
  `numero_personas` INT NOT NULL,
  `Usuario_clave` INT NOT NULL,
  `Mesa_numero_mesa` INT NOT NULL,
  PRIMARY KEY (`id_comanda`),
  INDEX `fk_Comanda_Usuario1_idx` (`Usuario_clave` ASC),
  INDEX `fk_Comanda_Mesa1_idx` (`Mesa_numero_mesa` ASC),
  CONSTRAINT `fk_Comanda_Usuario1`
    FOREIGN KEY (`Usuario_clave`)
    REFERENCES `mydb`.`Usuario` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comanda_Mesa1`
    FOREIGN KEY (`Mesa_numero_mesa`)
    REFERENCES `mydb`.`Mesa` (`numero_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Platillo` (
  `id_platillo` INT(11) NOT NULL AUTO_INCREMENT,
  `precio` DOUBLE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_platillo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `id_Pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NOT NULL,
  `Comanda_id_comanda` INT(11) NOT NULL,
  `Platillo_id_platillo` INT(11) NOT NULL,
  INDEX `fk_Pedido_Comanda1_idx` (`Comanda_id_comanda` ASC),
  PRIMARY KEY (`id_Pedido`),
  INDEX `fk_Pedido_Platillo1_idx` (`Platillo_id_platillo` ASC),
  CONSTRAINT `fk_Pedido_Comanda1`
    FOREIGN KEY (`Comanda_id_comanda`)
    REFERENCES `mydb`.`Comanda` (`id_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Platillo1`
    FOREIGN KEY (`Platillo_id_platillo`)
    REFERENCES `mydb`.`Platillo` (`id_platillo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `id_ticket` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `hora` DATETIME NOT NULL,
  `iva` FLOAT NOT NULL,
  `metodo` VARCHAR(45) NOT NULL,
  `total` DOUBLE NOT NULL,
  `Comanda_id_comanda` INT(11) NOT NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `fk_Ticket_Comanda1_idx` (`Comanda_id_comanda` ASC),
  CONSTRAINT `fk_Ticket_Comanda1`
    FOREIGN KEY (`Comanda_id_comanda`)
    REFERENCES `mydb`.`Comanda` (`id_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `mydb`.`platillo` (precio, nombre, categoria, estado, foto) VALUES
-- COMBINACIONES
(84, "Con Jamos, Tocino, Salchica, ó Longaniza", "Huevos", "disponible", "../fotos_menu/huevos.jpg"),
(84, "Al Albañil", "Huevos", "disponible","../fotos_menu/huevos.jpg"),
(84, "A la Mexicana", "Huevos", "disponible","../fotos_menu/huevos.jpg"),
(84, "Tirados", "Huevos", "disponible","../fotos_menu/huevos.jpg"),
(97, "Longaniza en Salsa Roja", "Con Hambre", "disponibles","../fotos_menu/huevos.jpg"),
(97, "Puntas de Filete a la Mexicana", "Con Hambre", "disponibles","../fotos_menu/huevos.jpg"),
(97, "Chicarron en Salaa Verde o Salsa Roja", "Con Hambre", "disponibles","../fotos_menu/huevos.jpg"),
(97, "Chilaquiles Rojos o Verdes", "Con Hambre", "disponibles","../fotos_menu/huevos.jpg"),
(75, "Tlayoyos", "Del Comal", "disponibles","../fotos_menu/huevos.jpg"),
(75, "Quesadilla Natural", "Del Comal", "disponibles","../fotos_menu/huevos.jpg"),
(75, "Trilogía de picaditas", "Del Comal", "disponibles","../fotos_menu/huevos.jpg"),
(75, "Memela Trsdicional", "Del Comal", "disponibles","../fotos_menu/huevos.jpg"),
(75, "Gorditas Jarochas", "Del Comal", "disponibles","../fotos_menu/huevos.jpg"),
-- LA CARTA
(79, "Huevos Rancheros", "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(97, "Huevos con Machaca", "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(89, "Huevos Achichcarrados", "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(70, 'Costra Especial "El Patio"' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(120, 'Costra Especial "El Patio"' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(86, 'Huevos en Casuela con Jocoque' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(89, 'Huevos del Mercado' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(81, 'Omelette' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(97, 'Omelette Poblano' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(89, 'Enchiladas' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(99, 'Enchiladas Suizas' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(85, 'Enfrijoladas "El Patio"' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(119, 'Cecina' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(99, 'Tacos de Cecina' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(79, 'Huevos Motuleños' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(53, 'Plato de fruta' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(46, 'Enzalada de Manzana' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(71, 'Hot Cakes (3 pzas.)' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
(15, 'Pan de Dulce (de la casa)' , "La Carta", "disponibles","../fotos_menu/huevos.jpg"),
-- BEBIDAS
(25, 'Americano' , "Bebidas calientes", "disponibles","../fotos_menu/huevos.jpg"),
(31, 'Expresso' , "Bebidas calientes", "disponibles","../fotos_menu/huevos.jpg"),
(32, 'Capuccino' , "Bebidas calientes", "disponibles","../fotos_menu/huevos.jpg"),
(35, 'Lechero' , "Bebidas calientes", "disponibles","../fotos_menu/huevos.jpg"),
(23, 'Té' , "Bebidas calientes", "disponibles","../fotos_menu/huevos.jpg"),
(33, 'Chocolate' , "Bebidas calientes", "disponibles","../fotos_menu/huevos.jpg"),
(25, 'Vaso Leche Chico' , "Bebidas calientes", "disponibles","../fotos_menu/huevos.jpg"),
(30, 'Vaso Leche Grande' , "Bebidas calientes", "disponibles","../fotos_menu/huevos.jpg"),
(35, 'Latte' , "Bebidas calientes", "disponibles","../fotos_menu/huevos.jpg"),

(39, 'Malteadas Fresa' , "Bebidas frias", "disponibles","../fotos_menu/huevos.jpg"),
(39, 'Malteadas Vainilla' , "Bebidas frias", "disponibles","../fotos_menu/huevos.jpg"),
(39, 'Malteadas Chocolate' , "Bebidas frias", "disponibles","../fotos_menu/huevos.jpg"),
(49, 'Ichi-koi Moka Oreo' , "Bebidas frias", "disponibles","../fotos_menu/huevos.jpg"),
(49, 'Ichi-koi Chips Ahoy' , "Bebidas frias", "disponibles","../fotos_menu/huevos.jpg"),
(49, 'Ichi-koi Clásico' , "Bebidas frias", "disponibles","../fotos_menu/huevos.jpg"),
(33, 'Chocomilk' , "Bebidas frias", "disponibles","../fotos_menu/huevos.jpg"),

(29, 'Vampiro. Chico(275 ml)' , "Bebidas Jugos", "disponibles","../fotos_menu/huevos.jpg"),
(37, 'Vampiro. Grnade(465 ml)' , "Bebidas Jugos", "disponibles","../fotos_menu/huevos.jpg"),
(29, 'Osasis. Chico(275 ml)' , "Bebidas Jugos", "disponibles","../fotos_menu/huevos.jpg"),
(37, 'Osasis. Grnade(465 ml)' , "Bebidas Jugos", "disponibles","../fotos_menu/huevos.jpg"),
(29, 'Verde. Chico(275 ml)' , "Bebidas Jugos", "disponibles","../fotos_menu/huevos.jpg"),
(37, 'Verde. Grnade(465 ml)' , "Bebidas Jugos", "disponibles","../fotos_menu/huevos.jpg"),

(31, "Cerveza", "Bebidas Pal' Alma", "disponibles","../fotos_menu/huevos.jpg"),
(39, "Michelada", "Bebidas Pal' Alma", "disponibles","../fotos_menu/huevos.jpg"),
(47, "Chelada", "Bebidas Pal' Alma", "disponibles","../fotos_menu/huevos.jpg"),

(28, "Refresco", "Bebidas Las Que Refrescan", "disponibles","../fotos_menu/huevos.jpg"),
(32, "Agua Mineral", "Bebidas Las Que Refrescan", "disponibles","../fotos_menu/huevos.jpg"),
(20, "Agua Embotellada", "Bebidas Las Que Refrescan", "disponibles","../fotos_menu/huevos.jpg"),
(35, "Soda Italiana", "Bebidas Las Que Refrescan", "disponibles","../fotos_menu/huevos.jpg"),
(32, "Rusa", "Bebidas Las Que Refrescan", "disponibles","../fotos_menu/huevos.jpg"),
(30, "Limonada", "Bebidas Las Que Refrescan", "disponibles","../fotos_menu/huevos.jpg"),
(30, "Naranjada", "Bebidas Las Que Refrescan", "disponibles","../fotos_menu/huevos.jpg"),
(42, "Agua de fresa con Avena", "Bebidas Las Que Refrescan", "disponibles","../fotos_menu/huevos.jpg"),
(35, "Lemon Stick", "Bebidas Las Que Refrescan", "disponibles","../fotos_menu/huevos.jpg"),
(35, "Conga", "Bebidas Las Que Refrescan", "disponibles", "../fotos_menu/huevos.jpg");
select * from mydb.platillo;

INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Ocupado');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');
INSERT INTO mesa(estado) values('Libre');

-- prubas para visualizar los elementos en cuenta
select * from mesa;
describe mesa;
UPDATE `mydb`.`mesa` SET `estado` = 'Ocupado' WHERE (`numero_mesa` = '1');
UPDATE `mydb`.`mesa` SET `estado` = 'Ocupado' WHERE (`numero_mesa` = '2');
UPDATE `mydb`.`mesa` SET `estado` = 'Ocupado' WHERE (`numero_mesa` = '3');

/* insercion de un tipo, usuario, comanda */
select * from tipo;
INSERT INTO `mydb`.`tipo` (`nombre_tipo`) VALUES ('comensal');
select * from usuario;
INSERT INTO `mydb`.`usuario` (`clave`, `apellido_paterno`, `apellido_materno`, `nombre`, `Tipo_id_tipo`) VALUES ('123', 'Castro', 'Arrollo', 'Maria Fernanda', '1');
select * from comanda;
INSERT INTO `mydb`.`comanda` (`hora_apertura`, `numero_personas`, `Usuario_clave`, `Mesa_numero_mesa`) VALUES ('2020-01-28 12:45:00', '3', '123', '1');
INSERT INTO `mydb`.`comanda` (`hora_apertura`, `numero_personas`, `Usuario_clave`, `Mesa_numero_mesa`) VALUES ('2020-01-28 13:00:00', '3', '123', '1');
INSERT INTO `mydb`.`comanda` (`hora_apertura`, `numero_personas`, `Usuario_clave`, `Mesa_numero_mesa`) VALUES ('2020-01-28 14:00:00', '3', '123', '1');
INSERT INTO `mydb`.`comanda` (`hora_apertura`, `numero_personas`, `Usuario_clave`, `Mesa_numero_mesa`) VALUES ('2020-01-28 12:50:00', '2', '123', '2');
INSERT INTO `mydb`.`comanda` (`hora_apertura`, `numero_personas`, `Usuario_clave`, `Mesa_numero_mesa`) VALUES ('2020-01-28 13:00:00', '1', '123', '3');
select * from platillo;
select * from pedido;
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '1', '1');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '1', '2');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '1', '3');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '2', '11');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '2', '12');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '3', '21');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '3', '22');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '3', '23');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '3', '24');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '3', '25');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '3', '26');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '3', '27');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '3', '28');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '5', '21');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '5', '22');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '5', '23');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '5', '24');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '5', '25');
INSERT INTO `mydb`.`pedido` (`comentario`, `Comanda_id_comanda`, `Platillo_id_platillo`) VALUES ('sin_comentario', '5', '26');
USE `mydb` ;
select * from comanda where Mesa_numero_mesa = 1 order by hora_apertura DESC limit 1;
select * from comanda where Mesa_numero_mesa = 3 order by hora_apertura DESC limit 1;
select * from comanda where Mesa_numero_mesa = 3 order by hora_apertura DESC limit 1;
select * from comanda where Mesa_numero_mesa = 1;
select * from comanda where Mesa_numero_mesa = 2 order by hora_apertura DESC limit 1;

select * from pedido where Comanda_id_comanda = 3;

select * from platillo where id_platillo = 21;
select * from platillo where id_platillo;

select sum(precio) from platillo;
 
select sum(precio) from 
pedido inner join platillo on
pedido.Platillo_id_platillo = platillo.id_platillo
where Comanda_id_comanda = 3;

select * from platillo;
